CREATE TABLE raw_api_payloads (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_name VARCHAR(100) NOT NULL,
    service_name VARCHAR(100) NOT NULL,
    request_url TEXT NOT NULL,
    request_params_json JSON NULL,
    response_body_json JSON NOT NULL,
    fetched_at DATETIME(6) NOT NULL,
    row_count INT NULL,
    status VARCHAR(30) NOT NULL,
    error_message TEXT NULL,
    PRIMARY KEY (id),
    INDEX idx_raw_api_payloads_source_fetched (source_name, service_name, fetched_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE metric_periods (
    id BIGINT NOT NULL AUTO_INCREMENT,
    period_code VARCHAR(20) NOT NULL,
    period_type VARCHAR(20) NOT NULL,
    year INT NOT NULL,
    quarter INT NULL,
    month INT NULL,
    start_date DATE NOT NULL,
    end_date DATE NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_metric_periods_period_code (period_code),
    INDEX idx_metric_periods_year_quarter_month (year, quarter, month)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE regions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    administrative_dong_code VARCHAR(20) NOT NULL,
    sido_code VARCHAR(20) NULL,
    sido_name VARCHAR(50) NOT NULL,
    sigungu_code VARCHAR(20) NULL,
    sigungu_name VARCHAR(50) NOT NULL,
    administrative_dong_name VARCHAR(50) NOT NULL,
    latitude DECIMAL(10, 7) NULL,
    longitude DECIMAL(10, 7) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_regions_administrative_dong_code (administrative_dong_code),
    INDEX idx_regions_sigungu_dong (sigungu_name, administrative_dong_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE legal_dongs (
    id BIGINT NOT NULL AUTO_INCREMENT,
    legal_dong_code VARCHAR(20) NOT NULL,
    sido_code VARCHAR(20) NULL,
    sido_name VARCHAR(50) NOT NULL,
    sigungu_code VARCHAR(20) NULL,
    sigungu_name VARCHAR(50) NOT NULL,
    legal_dong_name VARCHAR(50) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    effective_from DATE NULL,
    effective_to DATE NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_legal_dongs_legal_dong_code (legal_dong_code),
    INDEX idx_legal_dongs_sigungu_dong (sigungu_name, legal_dong_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE administrative_legal_dong_mappings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NOT NULL,
    legal_dong_id BIGINT NOT NULL,
    mapping_confidence DECIMAL(5, 4) NOT NULL DEFAULT 1.0000,
    mapping_rule VARCHAR(100) NOT NULL,
    effective_from DATE NULL,
    effective_to DATE NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_admin_legal_mapping (region_id, legal_dong_id, effective_from),
    CONSTRAINT fk_admin_legal_mapping_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_admin_legal_mapping_legal_dong FOREIGN KEY (legal_dong_id) REFERENCES legal_dongs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE business_categories (
    id BIGINT NOT NULL AUTO_INCREMENT,
    source_system VARCHAR(50) NOT NULL,
    source_category_code VARCHAR(30) NOT NULL,
    source_category_name VARCHAR(100) NOT NULL,
    large_category_code VARCHAR(30) NULL,
    large_category_name VARCHAR(100) NULL,
    medium_category_code VARCHAR(30) NULL,
    medium_category_name VARCHAR(100) NULL,
    small_category_code VARCHAR(30) NULL,
    small_category_name VARCHAR(100) NULL,
    normalized_category_code VARCHAR(30) NULL,
    normalized_category_name VARCHAR(100) NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_business_categories_source_code (source_system, source_category_code),
    INDEX idx_business_categories_normalized_code (normalized_category_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE category_code_mappings (
    id BIGINT NOT NULL AUTO_INCREMENT,
    seoul_service_category_code VARCHAR(30) NULL,
    small_business_category_code VARCHAR(30) NULL,
    ksic_code VARCHAR(30) NULL,
    normalized_category_code VARCHAR(30) NOT NULL,
    normalized_category_name VARCHAR(100) NULL,
    mapping_confidence DECIMAL(5, 4) NOT NULL,
    mapping_rule VARCHAR(100) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    INDEX idx_category_code_mappings_seoul (seoul_service_category_code),
    INDEX idx_category_code_mappings_small_business (small_business_category_code),
    INDEX idx_category_code_mappings_ksic (ksic_code),
    INDEX idx_category_code_mappings_normalized (normalized_category_code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_sales_by_dong_category_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    business_category_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    category_code_snapshot VARCHAR(30) NOT NULL,
    category_name_snapshot VARCHAR(100) NULL,
    sales_amount BIGINT NULL,
    sales_count BIGINT NULL,
    weekday_sales_amount BIGINT NULL,
    weekend_sales_amount BIGINT NULL,
    sales_by_day_json JSON NULL,
    sales_by_time_json JSON NULL,
    sales_by_demographic_json JSON NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_sales (region_id, business_category_id, metric_period_id),
    CONSTRAINT fk_source_seoul_sales_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_sales_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_sales_category FOREIGN KEY (business_category_id) REFERENCES business_categories (id),
    CONSTRAINT fk_source_seoul_sales_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_stores_by_dong_category_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    business_category_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    category_code_snapshot VARCHAR(30) NOT NULL,
    category_name_snapshot VARCHAR(100) NULL,
    store_count INT NULL,
    normal_store_count INT NULL,
    franchise_store_count INT NULL,
    open_rate DECIMAL(8, 4) NULL,
    open_store_count INT NULL,
    close_rate DECIMAL(8, 4) NULL,
    close_store_count INT NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_stores (region_id, business_category_id, metric_period_id),
    CONSTRAINT fk_source_seoul_stores_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_stores_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_stores_category FOREIGN KEY (business_category_id) REFERENCES business_categories (id),
    CONSTRAINT fk_source_seoul_stores_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_floating_population_by_dong_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    floating_population_total BIGINT NULL,
    floating_population_by_gender_json JSON NULL,
    floating_population_by_age_json JSON NULL,
    floating_population_by_day_json JSON NULL,
    floating_population_by_time_json JSON NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_floating_population (region_id, metric_period_id),
    CONSTRAINT fk_source_seoul_floating_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_floating_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_floating_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_resident_population_by_dong_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    resident_population_total BIGINT NULL,
    resident_population_by_gender_json JSON NULL,
    resident_population_by_age_json JSON NULL,
    household_count BIGINT NULL,
    household_type_json JSON NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_resident_population (region_id, metric_period_id),
    CONSTRAINT fk_source_seoul_resident_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_resident_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_resident_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_working_population_by_dong_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    working_population_total BIGINT NULL,
    working_population_male BIGINT NULL,
    working_population_female BIGINT NULL,
    working_population_by_age_json JSON NULL,
    working_population_male_by_age_json JSON NULL,
    working_population_female_by_age_json JSON NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_working_population (region_id, metric_period_id),
    CONSTRAINT fk_source_seoul_working_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_working_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_working_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_facilities_by_dong_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    facility_total_count INT NULL,
    public_office_count INT NULL,
    bank_count INT NULL,
    general_hospital_count INT NULL,
    hospital_count INT NULL,
    pharmacy_count INT NULL,
    kindergarten_count INT NULL,
    elementary_school_count INT NULL,
    middle_school_count INT NULL,
    high_school_count INT NULL,
    university_count INT NULL,
    department_store_count INT NULL,
    supermarket_count INT NULL,
    theater_count INT NULL,
    lodging_count INT NULL,
    railway_station_count INT NULL,
    subway_station_count INT NULL,
    bus_stop_count INT NULL,
    facility_detail_json JSON NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_facilities (region_id, metric_period_id),
    CONSTRAINT fk_source_seoul_facilities_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_facilities_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_facilities_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_seoul_apartments_by_dong_quarter (
    id BIGINT NOT NULL AUTO_INCREMENT,
    raw_api_payload_id BIGINT NULL,
    region_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    source_period_code VARCHAR(20) NOT NULL,
    region_code_snapshot VARCHAR(20) NOT NULL,
    region_name_snapshot VARCHAR(50) NULL,
    apartment_complex_count INT NULL,
    apartment_households_by_area_json JSON NULL,
    apartment_households_by_price_json JSON NULL,
    avg_apartment_area DECIMAL(12, 2) NULL,
    avg_apartment_market_price BIGINT NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_source_seoul_apartments (region_id, metric_period_id),
    CONSTRAINT fk_source_seoul_apartments_raw FOREIGN KEY (raw_api_payload_id) REFERENCES raw_api_payloads (id),
    CONSTRAINT fk_source_seoul_apartments_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_source_seoul_apartments_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE source_small_business_stores (
    id BIGINT NOT NULL AUTO_INCREMENT,
    external_store_id VARCHAR(50) NOT NULL,
    store_name VARCHAR(200) NULL,
    source_large_category_code VARCHAR(30) NULL,
    source_large_category_name VARCHAR(100) NULL,
    source_medium_category_code VARCHAR(30) NULL,
    source_medium_category_name VARCHAR(100) NULL,
    source_small_category_code VARCHAR(30) NULL,
    source_small_category_name VARCHAR(100) NULL,
    ksic_code VARCHAR(30) NULL,
    ksic_name VARCHAR(100) NULL,
    region_id BIGINT NULL,
    legal_dong_id BIGINT NULL,
    administrative_dong_code VARCHAR(20) NULL,
    legal_dong_code VARCHAR(20) NULL,
    jibun_address VARCHAR(300) NULL,
    road_address VARCHAR(300) NULL,
    longitude DECIMAL(11, 8) NULL,
    latitude DECIMAL(10, 8) NULL,
    snapshot_date DATE NOT NULL,
    source_updated_at DATETIME(6) NULL,
    source_row_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_small_business_stores_snapshot (external_store_id, snapshot_date),
    INDEX idx_small_business_stores_region_category (region_id, source_small_category_code, snapshot_date),
    INDEX idx_small_business_stores_location (latitude, longitude),
    CONSTRAINT fk_small_business_stores_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_small_business_stores_legal_dong FOREIGN KEY (legal_dong_id) REFERENCES legal_dongs (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE region_period_features (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    floating_population_total BIGINT NULL,
    floating_population_by_age_json JSON NULL,
    floating_population_by_time_json JSON NULL,
    resident_population_total BIGINT NULL,
    resident_population_by_age_json JSON NULL,
    household_count BIGINT NULL,
    working_population_total BIGINT NULL,
    working_population_by_age_json JSON NULL,
    facility_total_count INT NULL,
    facility_detail_json JSON NULL,
    apartment_complex_count INT NULL,
    apartment_detail_json JSON NULL,
    daytime_population_ratio DECIMAL(8, 4) NULL,
    night_population_ratio DECIMAL(8, 4) NULL,
    weekend_population_ratio DECIMAL(8, 4) NULL,
    residential_demand_score DECIMAL(8, 4) NULL,
    office_demand_score DECIMAL(8, 4) NULL,
    attraction_score DECIMAL(8, 4) NULL,
    traffic_access_score DECIMAL(8, 4) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_region_period_features (region_id, metric_period_id),
    CONSTRAINT fk_region_period_features_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_region_period_features_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE region_cost_features (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NULL,
    legal_dong_id BIGINT NULL,
    metric_period_id BIGINT NOT NULL,
    region_level VARCHAR(30) NOT NULL,
    source_region_code VARCHAR(30) NULL,
    source_region_name VARCHAR(100) NULL,
    property_type VARCHAR(50) NULL,
    rent_amount DECIMAL(18, 2) NULL,
    rent_index DECIMAL(12, 4) NULL,
    vacancy_rate DECIMAL(8, 4) NULL,
    investment_return_rate DECIMAL(8, 4) NULL,
    commercial_transaction_count INT NULL,
    median_commercial_price_per_area DECIMAL(18, 2) NULL,
    price_growth_rate DECIMAL(8, 4) NULL,
    rent_pressure_score DECIMAL(8, 4) NULL,
    vacancy_risk_score DECIMAL(8, 4) NULL,
    fixed_cost_burden_index DECIMAL(8, 4) NULL,
    location_cost_score DECIMAL(8, 4) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_region_cost_features (region_id, legal_dong_id, metric_period_id, region_level, property_type),
    CONSTRAINT fk_region_cost_features_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_region_cost_features_legal_dong FOREIGN KEY (legal_dong_id) REFERENCES legal_dongs (id),
    CONSTRAINT fk_region_cost_features_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE region_built_environment_features (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NULL,
    legal_dong_id BIGINT NULL,
    metric_period_id BIGINT NOT NULL,
    commercial_building_count INT NULL,
    avg_building_age DECIMAL(8, 2) NULL,
    avg_gross_floor_area DECIMAL(18, 2) NULL,
    parking_capacity_proxy DECIMAL(12, 4) NULL,
    commercial_floor_area_proxy DECIMAL(18, 2) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_region_built_environment_features (region_id, legal_dong_id, metric_period_id),
    CONSTRAINT fk_built_environment_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_built_environment_legal_dong FOREIGN KEY (legal_dong_id) REFERENCES legal_dongs (id),
    CONSTRAINT fk_built_environment_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE commercial_metric_snapshots (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NOT NULL,
    business_category_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    sales_amount BIGINT NULL,
    sales_count BIGINT NULL,
    avg_ticket_amount DECIMAL(18, 2) NULL,
    weekday_sales_amount BIGINT NULL,
    weekend_sales_amount BIGINT NULL,
    sales_by_day_json JSON NULL,
    sales_by_time_json JSON NULL,
    sales_by_demographic_json JSON NULL,
    store_count INT NULL,
    normal_store_count INT NULL,
    franchise_store_count INT NULL,
    open_store_count INT NULL,
    close_store_count INT NULL,
    open_rate DECIMAL(8, 4) NULL,
    close_rate DECIMAL(8, 4) NULL,
    sales_growth_rate_qoq DECIMAL(8, 4) NULL,
    sales_growth_rate_yoy DECIMAL(8, 4) NULL,
    store_growth_rate_qoq DECIMAL(8, 4) NULL,
    franchise_ratio DECIMAL(8, 4) NULL,
    competition_intensity_score DECIMAL(8, 4) NULL,
    demand_score DECIMAL(8, 4) NULL,
    market_score DECIMAL(8, 4) NULL,
    stability_score DECIMAL(8, 4) NULL,
    closure_risk_signal DECIMAL(8, 4) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_commercial_metric_snapshots (region_id, business_category_id, metric_period_id),
    INDEX idx_commercial_metric_snapshots_category_period (business_category_id, metric_period_id),
    CONSTRAINT fk_commercial_metric_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_commercial_metric_category FOREIGN KEY (business_category_id) REFERENCES business_categories (id),
    CONSTRAINT fk_commercial_metric_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE model_feature_snapshots (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NOT NULL,
    business_category_id BIGINT NOT NULL,
    metric_period_id BIGINT NOT NULL,
    feature_json JSON NOT NULL,
    label_json JSON NULL,
    feature_version VARCHAR(30) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    UNIQUE KEY uk_model_feature_snapshots (region_id, business_category_id, metric_period_id, feature_version),
    CONSTRAINT fk_model_feature_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_model_feature_category FOREIGN KEY (business_category_id) REFERENCES business_categories (id),
    CONSTRAINT fk_model_feature_period FOREIGN KEY (metric_period_id) REFERENCES metric_periods (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE analysis_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    region_id BIGINT NULL,
    business_category_id BIGINT NULL,
    input_address VARCHAR(300) NULL,
    latitude DECIMAL(10, 8) NULL,
    longitude DECIMAL(11, 8) NULL,
    user_budget BIGINT NULL,
    user_max_rent BIGINT NULL,
    target_monthly_sales BIGINT NULL,
    preferred_area_square_meter DECIMAL(12, 2) NULL,
    operation_type VARCHAR(50) NULL,
    franchise_yn BOOLEAN NULL,
    target_customer_json JSON NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    INDEX idx_analysis_requests_region_category (region_id, business_category_id),
    CONSTRAINT fk_analysis_requests_region FOREIGN KEY (region_id) REFERENCES regions (id),
    CONSTRAINT fk_analysis_requests_category FOREIGN KEY (business_category_id) REFERENCES business_categories (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE analysis_results (
    id BIGINT NOT NULL AUTO_INCREMENT,
    analysis_request_id BIGINT NOT NULL,
    model_feature_snapshot_id BIGINT NULL,
    success_score DECIMAL(8, 4) NULL,
    closure_risk_score DECIMAL(8, 4) NULL,
    location_fit_score DECIMAL(8, 4) NULL,
    recommendation_grade VARCHAR(10) NULL,
    positive_factors_json JSON NULL,
    risk_factors_json JSON NULL,
    strategy_json JSON NULL,
    model_output_json JSON NULL,
    ai_summary TEXT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (id),
    CONSTRAINT fk_analysis_results_request FOREIGN KEY (analysis_request_id) REFERENCES analysis_requests (id),
    CONSTRAINT fk_analysis_results_model_feature FOREIGN KEY (model_feature_snapshot_id) REFERENCES model_feature_snapshots (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
